# Generated by Django 5.0.14 on 2026-07-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
