# Generated by Django 5.0.14 on 2026-07-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
